# Generated by Django 4.1.3 on 2022-12-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ad_description_alter_ad_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(null=True, upload_to='ads/%Y/%m/%d/'),
        ),
    ]
